### ISSUE TITLE
add AddItem has a bug 

### ISSUE THREAD

**Issue by quan-xie** [el10savio/Inverted-Index-Generator#1]
Items   []InvertedIndexItem shoud change Items   []*InvertedIndexItem

**Comment by el10savio** [comment]
Thanks a lot for pointing it out! I'll update it.

**Comment by el10savio** [comment]
[Commit 1163a47](https://github.com/el10savio/Inverted-Index-Generator/commit/1163a476912b5be96534d9601c4ad2662e84d0e9)
